// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5571.WestCoastTest;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveLeftWheels;
    public static CANTalon driveRightWheels;
    public static RobotDrive driveRobotDrive21;
  

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static CANTalon driveLeftWheelSlave;
    public static CANTalon driveRightWheelSlave;
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftWheels = new CANTalon(1);
        driveLeftWheels.setInverted(true);
        driveLeftWheels.reverseOutput(true);
        
        LiveWindow.addActuator("Drive", "LeftWheels", driveLeftWheels);
        driveLeftWheelSlave = new CANTalon(3);
        driveLeftWheelSlave.changeControlMode(TalonControlMode.Follower);
        driveLeftWheelSlave.set(driveLeftWheels.getDeviceID());
        LiveWindow.addActuator("Drive", "LeftWheelsSlave", driveLeftWheelSlave);
        
        driveRightWheels = new CANTalon(2);
        LiveWindow.addActuator("Drive", "RightWheels", driveRightWheels);
        driveRightWheelSlave = new CANTalon(4);
        driveRightWheelSlave.changeControlMode(TalonControlMode.Follower);
        driveRightWheelSlave.set(driveRightWheels.getDeviceID());
        LiveWindow.addActuator("Drive", "RightWheelSlave", driveRightWheelSlave);
        
        driveRobotDrive21 = new RobotDrive(driveLeftWheels, driveRightWheels);
        
        driveRobotDrive21.setSafetyEnabled(true);
        driveRobotDrive21.setExpiration(0.1);
        driveRobotDrive21.setSensitivity(0.5);
        driveRobotDrive21.setMaxOutput(1.0);
        driveRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
